version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker_postgre_init.sql:/docker-entrypoint-initdb.d/docker_postgre_init.sql
  
# this service will initiate the pgadmin application
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      #PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      #PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      -  "5050:80"
    depends_on:
      - database

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: